/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import model.AutomatoFinitoDeterministico;
import model.Estado;

/**
 *
 * @author heito
 */
public class TelaCriarAutomato_EstadoInicial extends javax.swing.JFrame {
    private List<AutomatoFinitoDeterministico> automatosRecebidos;
    private AutomatoFinitoDeterministico automatoRecebido = new AutomatoFinitoDeterministico();
    private List<Estado> estados = new ArrayList<>();
    private String todosEstados, estadoInformacao;
    private String verificarVazio;
    /**
     * Creates new form TelaCriarAutomato_EstadoInicial
     */
    public TelaCriarAutomato_EstadoInicial(List<AutomatoFinitoDeterministico> automatos, AutomatoFinitoDeterministico automato) {
        this.automatosRecebidos = automatos;
        this.automatoRecebido = automato;
        initComponents();
        mostrarEstados();
    }
    
    public TelaCriarAutomato_EstadoInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mensagemDefinirEstadoInicial = new javax.swing.JLabel();
        txtEstadoInicial = new javax.swing.JTextField();
        botaoDefinirEstadoInicial = new javax.swing.JButton();
        jTodosEstados = new javax.swing.JLabel();
        mensagemEstadoInicial = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mensagemDefinirEstadoInicial.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mensagemDefinirEstadoInicial.setText("Digite o nome do estado inicial:");

        txtEstadoInicial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEstadoInicialKeyPressed(evt);
            }
        });

        botaoDefinirEstadoInicial.setText("Definir Estado Inicial");
        botaoDefinirEstadoInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDefinirEstadoInicialActionPerformed(evt);
            }
        });

        jTodosEstados.setText("jLabel1");

        mensagemEstadoInicial.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mensagemEstadoInicial.setText("Veja abaixo os estados que você criou e escolha o estado inicial");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mensagemEstadoInicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(mensagemDefinirEstadoInicial, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTodosEstados, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txtEstadoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(botaoDefinirEstadoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(mensagemEstadoInicial)
                .addGap(18, 18, 18)
                .addComponent(jTodosEstados, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(mensagemDefinirEstadoInicial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEstadoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(botaoDefinirEstadoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void mostrarEstados(){
        jTodosEstados.setText(automatoRecebido.getEstados().toString());
    }
    
    private void definirEstadoInicial(){
        verificarVazio = txtEstadoInicial.getText();
        if(verificarVazio.equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(null, "Campo Vazio!!! Escolha um estado existente");
        }
        else{
            Estado estadoInicial = null;
            String nomeEstadoInicial;
            
            nomeEstadoInicial = txtEstadoInicial.getText();
            for (Estado estado : automatoRecebido.getEstados()) {
                if ((estado.getNome().equals(nomeEstadoInicial) && estado.isFinal()==false) ) {
                    estadoInicial = estado;
                    break;
                }
            }
            
            
            if (estadoInicial == null) {
                JOptionPane.showMessageDialog(null, "Estado inicial inválido. Escolha outro");
            }
            else{
                automatoRecebido.setEstadoInicial(estadoInicial);
                TelaCriarAutomato_Alfabeto telaCriarAutomatoAlfabeto = new TelaCriarAutomato_Alfabeto(automatosRecebidos, automatoRecebido);
                telaCriarAutomatoAlfabeto.setVisible(true);
                this.dispose();
            }
        }
    }
    
    private void botaoDefinirEstadoInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDefinirEstadoInicialActionPerformed
        // TODO add your handling code here:
        definirEstadoInicial();
    }//GEN-LAST:event_botaoDefinirEstadoInicialActionPerformed

    private void txtEstadoInicialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEstadoInicialKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            definirEstadoInicial();
        }
    }//GEN-LAST:event_txtEstadoInicialKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCriarAutomato_EstadoInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCriarAutomato_EstadoInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCriarAutomato_EstadoInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCriarAutomato_EstadoInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCriarAutomato_EstadoInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoDefinirEstadoInicial;
    private javax.swing.JLabel jTodosEstados;
    private javax.swing.JLabel mensagemDefinirEstadoInicial;
    private javax.swing.JLabel mensagemEstadoInicial;
    private javax.swing.JTextField txtEstadoInicial;
    // End of variables declaration//GEN-END:variables
}
