/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import model.AutomatoFinitoDeterministico;
import model.Estado;
import model.Transicao;

/**
 *
 * @author heito
 */
public class TelaCriarAutomato_QuantidadeTransicoes extends javax.swing.JFrame {
    private List<AutomatoFinitoDeterministico> automatosRecebidos;
    private AutomatoFinitoDeterministico automatoRecebido = new AutomatoFinitoDeterministico();
    private String verificarVazioQuantidadeTransicoes, verificarVazioEstadoOrigem, verificarVazioSimbolo, verificarVazioEstadoDestino;
    private int numeroTransicoes, contadorTransicao = 1;
    private String todosEstados="", estadoInicial, alfabeto="";
    /**
     * Creates new form TelaCriarAutomato_Transicoes
     */
    public TelaCriarAutomato_QuantidadeTransicoes(List<AutomatoFinitoDeterministico> automatos, AutomatoFinitoDeterministico automato) {
        this.automatosRecebidos = automatos;
        this.automatoRecebido = automato;
        initComponents();
    }
    
    public TelaCriarAutomato_QuantidadeTransicoes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mensagemPerguntaTransicoes = new javax.swing.JLabel();
        txtQuantidadeTransicoes = new javax.swing.JTextField();
        botaoConfirmarQuantidadeTransicoes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mensagemPerguntaTransicoes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mensagemPerguntaTransicoes.setText("Quantas transições o Automato terá?");

        txtQuantidadeTransicoes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQuantidadeTransicoesKeyPressed(evt);
            }
        });

        botaoConfirmarQuantidadeTransicoes.setText("Confirmar Quantidade de Transições");
        botaoConfirmarQuantidadeTransicoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConfirmarQuantidadeTransicoesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botaoConfirmarQuantidadeTransicoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mensagemPerguntaTransicoes, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                    .addComponent(txtQuantidadeTransicoes))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(mensagemPerguntaTransicoes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtQuantidadeTransicoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(botaoConfirmarQuantidadeTransicoes)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void informarQuantidadeTransicoes(){
        verificarVazioQuantidadeTransicoes = txtQuantidadeTransicoes.getText();
        if (verificarVazioQuantidadeTransicoes.equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "Campo Vazio!!! Digite a quantidade de transicoes");
        } else {
            numeroTransicoes = Integer.parseInt(verificarVazioQuantidadeTransicoes);
            if (numeroTransicoes <= 0) {
                JOptionPane.showMessageDialog(null, "Transicoes Insuficientes!!! Digite uma quantidade maior");
            } else {
                TelaCriarAutomato_Transicoes telaCriarAutomatoTransicoes = new TelaCriarAutomato_Transicoes(automatosRecebidos, automatoRecebido, numeroTransicoes);
                telaCriarAutomatoTransicoes.setVisible(true);
                this.dispose();
            }
        }
    }
    
    private void botaoConfirmarQuantidadeTransicoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConfirmarQuantidadeTransicoesActionPerformed
        // TODO add your handling code here:
        informarQuantidadeTransicoes();
    }//GEN-LAST:event_botaoConfirmarQuantidadeTransicoesActionPerformed

    private void txtQuantidadeTransicoesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantidadeTransicoesKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            informarQuantidadeTransicoes();
        }
    }//GEN-LAST:event_txtQuantidadeTransicoesKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCriarAutomato_QuantidadeTransicoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCriarAutomato_QuantidadeTransicoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCriarAutomato_QuantidadeTransicoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCriarAutomato_QuantidadeTransicoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCriarAutomato_QuantidadeTransicoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoConfirmarQuantidadeTransicoes;
    private javax.swing.JLabel mensagemPerguntaTransicoes;
    private javax.swing.JTextField txtQuantidadeTransicoes;
    // End of variables declaration//GEN-END:variables
}
