/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import model.AutomatoFinitoDeterministico;
import model.Estado;

/**
 *
 * @author heito
 */
public class TelaCriarAutomato_Alfabeto extends javax.swing.JFrame {
    private List<AutomatoFinitoDeterministico> automatosRecebidos;
    private AutomatoFinitoDeterministico automatoRecebido = new AutomatoFinitoDeterministico();
    private String verificarVazio;
    private List<Character> alfabetos = new ArrayList<>();
    private String alfabeto;
    /**
     * Creates new form TelaCriarAutomato_Alfabeto
     */
    public TelaCriarAutomato_Alfabeto(List<AutomatoFinitoDeterministico> automatos, AutomatoFinitoDeterministico automato) {
        this.automatosRecebidos = automatos;
        this.automatoRecebido = automato;
        initComponents();
    }
    
    public TelaCriarAutomato_Alfabeto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelDigitarSimbolo = new javax.swing.JLabel();
        botaoConfirmarAlfabeto = new javax.swing.JButton();
        txtAlfabeto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelDigitarSimbolo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelDigitarSimbolo.setText("Digite os simbolos do alfabeto, separados por espaço:");

        botaoConfirmarAlfabeto.setText("Confirmar Alfabeto");
        botaoConfirmarAlfabeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConfirmarAlfabetoActionPerformed(evt);
            }
        });

        txtAlfabeto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAlfabetoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelDigitarSimbolo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtAlfabeto)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(botaoConfirmarAlfabeto, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabelDigitarSimbolo)
                .addGap(18, 18, 18)
                .addComponent(txtAlfabeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(botaoConfirmarAlfabeto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void adicionarAlfabeto(){
        verificarVazio = txtAlfabeto.getText();
        if(verificarVazio.equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(null, "Campo Vazio!!! Digite um alfabeto para esse automato");
        }
        else{
            alfabeto = verificarVazio;
            for (char simboloAlfabeto : alfabeto.toCharArray()) {
                if (simboloAlfabeto != ' ') {
                    alfabetos.add(simboloAlfabeto);
                }
            }
            automatoRecebido.setAlfabeto(alfabetos);
            
            TelaCriarAutomato_QuantidadeTransicoes telaCriarAutomatoQuantidadeTransicoes = new TelaCriarAutomato_QuantidadeTransicoes(automatosRecebidos, automatoRecebido);
            telaCriarAutomatoQuantidadeTransicoes.setVisible(true);
            this.dispose();
        }
        
    }
    
    private void botaoConfirmarAlfabetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConfirmarAlfabetoActionPerformed
        // TODO add your handling code here:
        adicionarAlfabeto();
    }//GEN-LAST:event_botaoConfirmarAlfabetoActionPerformed

    private void txtAlfabetoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAlfabetoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            adicionarAlfabeto();
        }
    }//GEN-LAST:event_txtAlfabetoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCriarAutomato_Alfabeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCriarAutomato_Alfabeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCriarAutomato_Alfabeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCriarAutomato_Alfabeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCriarAutomato_Alfabeto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoConfirmarAlfabeto;
    private javax.swing.JLabel jLabelDigitarSimbolo;
    private javax.swing.JTextField txtAlfabeto;
    // End of variables declaration//GEN-END:variables
}
