/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import model.AutomatoFinitoDeterministico;
import model.Estado;
import model.Transicao;

/**
 *
 * @author heito
 */
public class TelaCriarAutomato_Nome extends javax.swing.JFrame {
    private List<AutomatoFinitoDeterministico> automatosRecebidos;
    private AutomatoFinitoDeterministico automato = new AutomatoFinitoDeterministico();
    private String verificarVazio;
    /**
     * Creates new form TelaCriarAutomato
     */
    public TelaCriarAutomato_Nome(List<AutomatoFinitoDeterministico> automatos) {
        this.automatosRecebidos = automatos;
        initComponents();
    }
    
    public TelaCriarAutomato_Nome() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mensagemParaNomeAutomato = new javax.swing.JLabel();
        txtNomeParaAutomato = new javax.swing.JTextField();
        confirmarNome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mensagemParaNomeAutomato.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mensagemParaNomeAutomato.setText("Digite um nome para o automato:");

        txtNomeParaAutomato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeParaAutomatoKeyPressed(evt);
            }
        });

        confirmarNome.setText("Confirmar Nome");
        confirmarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarNomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mensagemParaNomeAutomato)
                            .addComponent(txtNomeParaAutomato, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(confirmarNome)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(mensagemParaNomeAutomato)
                .addGap(28, 28, 28)
                .addComponent(txtNomeParaAutomato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(confirmarNome)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private boolean verificarNomeExistente(){
        for (AutomatoFinitoDeterministico automato : automatosRecebidos) {
            if (automato.getNome().equalsIgnoreCase(verificarVazio)) {
                return false;
            }
        }
        return true;
    }
    
    private void definirNome(){
        verificarVazio = txtNomeParaAutomato.getText();
        boolean nomeExistente;
        if(verificarVazio.equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(null, "Campo Vazio!!! Digite um nome para o Automato");
        }
        else{
            nomeExistente = verificarNomeExistente();
            if(nomeExistente){
                automato.setNome(verificarVazio);
                TelaCriarAutomato_QuantidadeEstados telaCriarAutomatoQuantidadeEstados = new TelaCriarAutomato_QuantidadeEstados(automatosRecebidos, automato);
                telaCriarAutomatoQuantidadeEstados.setVisible(true);
                this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(null, "Esse nome já existe!!! Digite outro nome para o Automato");

            }
            
        }
            
    }
    
    private void confirmarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarNomeActionPerformed
        // TODO add your handling code here:
        definirNome();
    }//GEN-LAST:event_confirmarNomeActionPerformed

    private void txtNomeParaAutomatoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeParaAutomatoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            definirNome();
        }
    }//GEN-LAST:event_txtNomeParaAutomatoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCriarAutomato_Nome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCriarAutomato_Nome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCriarAutomato_Nome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCriarAutomato_Nome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCriarAutomato_Nome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmarNome;
    private javax.swing.JLabel mensagemParaNomeAutomato;
    private javax.swing.JTextField txtNomeParaAutomato;
    // End of variables declaration//GEN-END:variables
}
