/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.JOptionPane;
import model.AutomatoFinitoDeterministico;
import model.Estado;
import model.Transicao;

/**
 *
 * @author heito
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private List<AutomatoFinitoDeterministico> automatos;

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal(List<AutomatoFinitoDeterministico> automatos) {
        this.automatos = automatos;
        initComponents();
    }
    
    public TelaPrincipal() {
        initComponents();
        
        Estado q0 = new Estado("q0", false);
        Estado q1 = new Estado("q1", true);
        List<Estado> estados = Arrays.asList(q0, q1);
        List<Transicao> transicoes = Arrays.asList(new Transicao(q0, 'a', q1), new Transicao(q1, 'b', q0), new Transicao(q1, 'a', q1), new Transicao(q0, 'b', q0));
        List<Character> alfabeto = Arrays.asList('a', 'b');
        
        AutomatoFinitoDeterministico automatoFinito = new AutomatoFinitoDeterministico("TerminaComA", estados, q0, transicoes, alfabeto);
        automatos = new ArrayList<>();
        automatos.add(automatoFinito);
        
        Estado estado0 = new Estado("q0", false);  // Estado inicial
        Estado estado1 = new Estado("q1", false);  // Último símbolo foi 'a'
        Estado estado2 = new Estado("q2", true);   // Estado de aceitação (termina com 'ab')
        List<Estado> estadosInicioA_FimB = Arrays.asList(estado0, estado1, estado2);

        List<Transicao> transicoesInicioAFimB = Arrays.asList(
                new Transicao(estado0, 'a', estado1),
                new Transicao(estado0, 'b', estado0), // Não pode começar com 'b'
                new Transicao(estado1, 'a', estado1),
                new Transicao(estado1, 'b', estado2),
                new Transicao(estado2, 'a', estado1),
                new Transicao(estado2, 'b', estado2)
        );

        List<Character> alfabetoInicioAFimB = Arrays.asList('a', 'b');

        AutomatoFinitoDeterministico ComecaComA_TerminaComB = new AutomatoFinitoDeterministico(
                "ComecaComA_TerminaComB",
                estadosInicioA_FimB,
                estado0,
                transicoesInicioAFimB,
                alfabetoInicioAFimB
        );
        automatos.add(ComecaComA_TerminaComB);
        
        Estado estado3 = new Estado("q0", false);  // Estado inicial
        Estado estado4 = new Estado("q1", false);  // Último símbolo foi 'a'
        Estado estado5 = new Estado("q2", true);   // Estado de aceitação (termina com 'ab')
        List<Estado> estados3 = Arrays.asList(estado3, estado4, estado5);

        List<Transicao> transicoes3 = Arrays.asList(
                new Transicao(estado3, 'a', estado4),
                new Transicao(estado3, 'b', estado3),
                new Transicao(estado4, 'a', estado4),
                new Transicao(estado4, 'b', estado5),
                new Transicao(estado5, 'a', estado4),
                new Transicao(estado5, 'b', estado3)
        );

        List<Character> alfabeto3 = Arrays.asList('a', 'b');

        AutomatoFinitoDeterministico automatoFinitoTerminaAB = new AutomatoFinitoDeterministico(
                "TerminaComAB",
                estados3,
                estado3,
                transicoes3,
                alfabeto3
        );

        automatos.add(automatoFinitoTerminaAB);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoCriarAutomato = new javax.swing.JButton();
        botaoVerHistorico = new javax.swing.JButton();
        botaoSair = new javax.swing.JButton();
        botaoSobre = new javax.swing.JButton();
        mensagemBoasVindas1 = new javax.swing.JLabel();
        mensagemBoasVindas2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botaoCriarAutomato.setBackground(new java.awt.Color(0, 0, 255));
        botaoCriarAutomato.setText("CRIAR AUTOMATO");
        botaoCriarAutomato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCriarAutomatoActionPerformed(evt);
            }
        });

        botaoVerHistorico.setBackground(new java.awt.Color(0, 255, 0));
        botaoVerHistorico.setText("VISUALIZAR HISTÓRICO");
        botaoVerHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVerHistoricoActionPerformed(evt);
            }
        });

        botaoSair.setText("SAIR");
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });

        botaoSobre.setText("SOBRE");
        botaoSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSobreActionPerformed(evt);
            }
        });

        mensagemBoasVindas1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        mensagemBoasVindas1.setText("Bem-vindo ao FiniteVisual");

        mensagemBoasVindas2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mensagemBoasVindas2.setText("Simulador de Automatos Finitos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botaoSair)
                            .addComponent(botaoSobre, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(botaoCriarAutomato, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(95, 95, 95)
                                .addComponent(botaoVerHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mensagemBoasVindas2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mensagemBoasVindas1))))
                        .addGap(0, 94, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botaoSobre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(mensagemBoasVindas1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mensagemBoasVindas2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCriarAutomato, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoVerHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(118, 118, 118)
                .addComponent(botaoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void sobre(){
        JOptionPane.showMessageDialog(null,"Projeto desenvolvido para a disciplina de Teoria da Computação"
                + "\nDesenvolvido por: Heitor Vinicius");
    }
    
    private void sair() {
        Object[] opcao = {"Sim", "Não"};
        int opcaoSelecionada = JOptionPane.showOptionDialog(this, "Deseja realmente sair?", "Aviso",
                JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, opcao, opcao[0]);
        if (opcaoSelecionada == 0) {
            this.dispose();
        }
    }
    
    
    
    private void botaoSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSobreActionPerformed
        // TODO add your handling code here:
        sobre();
    }//GEN-LAST:event_botaoSobreActionPerformed

    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed
        // TODO add your handling code here:
        sair();
    }//GEN-LAST:event_botaoSairActionPerformed

    private void botaoCriarAutomatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCriarAutomatoActionPerformed
        // TODO add your handling code here:
        TelaCriarAutomato_Nome telaCriarAutomatoNome = new TelaCriarAutomato_Nome(automatos);
        telaCriarAutomatoNome.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botaoCriarAutomatoActionPerformed

    private void botaoVerHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVerHistoricoActionPerformed
        // TODO add your handling code here:
        TelaVerHistorico telaVerHistorico = new TelaVerHistorico(automatos);
        telaVerHistorico.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botaoVerHistoricoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCriarAutomato;
    private javax.swing.JButton botaoSair;
    private javax.swing.JButton botaoSobre;
    private javax.swing.JButton botaoVerHistorico;
    private javax.swing.JLabel mensagemBoasVindas1;
    private javax.swing.JLabel mensagemBoasVindas2;
    // End of variables declaration//GEN-END:variables
}
