/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import model.AutomatoFinitoDeterministico;
import model.Estado;

/**
 *
 * @author heito
 */
public class TelaCriarAutomato_Estado extends javax.swing.JFrame {
    private List<AutomatoFinitoDeterministico> automatosRecebidos;
    private AutomatoFinitoDeterministico automatoRecebido = new AutomatoFinitoDeterministico();
    private List<Estado> estados = new ArrayList<>();
    private String verificarVazioEstado;
    private int numeroEstados;
    private int contadorEstados = 1;
    /**
     * Creates new form TelaCriarAutomato_Estado
     */
    public TelaCriarAutomato_Estado(List<AutomatoFinitoDeterministico> automatos, AutomatoFinitoDeterministico automato, int numeroEstados) {
        this.automatosRecebidos = automatos;
        this.automatoRecebido = automato;
        this.numeroEstados = numeroEstados;
        initComponents();
        atualizarPosicaoEstado();
    }
    
    public TelaCriarAutomato_Estado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoGrupoIsFinal = new javax.swing.ButtonGroup();
        jEstadoPosicao = new javax.swing.JLabel();
        txtNomeEstado = new javax.swing.JTextField();
        botaoAdicionarEstado = new javax.swing.JButton();
        jEstadoIsFinal = new javax.swing.JLabel();
        jRadioButtonSim = new javax.swing.JRadioButton();
        jRadioButtonNao = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jEstadoPosicao.setText("jLabel1");

        txtNomeEstado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeEstadoKeyPressed(evt);
            }
        });

        botaoAdicionarEstado.setText("Adicionar Estado");
        botaoAdicionarEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAdicionarEstadoActionPerformed(evt);
            }
        });

        jEstadoIsFinal.setText("Esse estado é o final?");

        botaoGrupoIsFinal.add(jRadioButtonSim);
        jRadioButtonSim.setText("Sim");

        botaoGrupoIsFinal.add(jRadioButtonNao);
        jRadioButtonNao.setText("Não");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonNao)
                    .addComponent(jRadioButtonSim)
                    .addComponent(jEstadoPosicao)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(botaoAdicionarEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jEstadoIsFinal, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                        .addComponent(txtNomeEstado)))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jEstadoPosicao)
                .addGap(18, 18, 18)
                .addComponent(txtNomeEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jEstadoIsFinal)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonSim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonNao)
                .addGap(20, 20, 20)
                .addComponent(botaoAdicionarEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void atualizarPosicaoEstado() {
        jEstadoPosicao.setText("Digite o nome do estado " + (contadorEstados) + ":");
    } 
    
    private void reiniciarCriarEstado(){
        contadorEstados = 1;
        atualizarPosicaoEstado();
    }
    
    private void adicionarEstado() {
        verificarVazioEstado = txtNomeEstado.getText();
        if (verificarVazioEstado.equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "Campo Vazio!!! Digite um nome para o estado"
                    + " ou diga se ele é o final ou não");
            reiniciarCriarEstado();
        }
        else{
            boolean isFinal=false;
            boolean estadoFinalExiste = false;
            
            if(jRadioButtonSim.isSelected())
                isFinal = true;
            
            estados.add(new Estado(txtNomeEstado.getText(), isFinal));

            if (contadorEstados == numeroEstados) {
                for (Estado estado : estados) {
                    if (estado.isFinal() == true) {
                        estadoFinalExiste = true;
                        break;
                    }
                }
                if (estadoFinalExiste == false) {
                    JOptionPane.showMessageDialog(null, "Não existe estado final. Crie novamente os estados");
                    estados.removeAll(estados);
                    txtNomeEstado.setText("");
                    reiniciarCriarEstado();
                } else {
                    JOptionPane.showMessageDialog(null, "Estados criados");
                    automatoRecebido.setEstados(estados);
                    TelaCriarAutomato_EstadoInicial telaCriarAutomatoEstadoInicial = new TelaCriarAutomato_EstadoInicial(automatosRecebidos, automatoRecebido);
                    telaCriarAutomatoEstadoInicial.setVisible(true);
                    this.dispose();
                }
            } else {
                contadorEstados++;
                atualizarPosicaoEstado();
                botaoGrupoIsFinal.clearSelection();
                txtNomeEstado.setText("");
            }
        }
    }
    
    private void botaoAdicionarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAdicionarEstadoActionPerformed
        // TODO add your handling code here:
        adicionarEstado();
    }//GEN-LAST:event_botaoAdicionarEstadoActionPerformed

    private void txtNomeEstadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeEstadoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            adicionarEstado();
        }
    }//GEN-LAST:event_txtNomeEstadoKeyPressed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCriarAutomato_Estado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCriarAutomato_Estado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCriarAutomato_Estado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCriarAutomato_Estado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCriarAutomato_Estado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAdicionarEstado;
    private javax.swing.ButtonGroup botaoGrupoIsFinal;
    private javax.swing.JLabel jEstadoIsFinal;
    private javax.swing.JLabel jEstadoPosicao;
    private javax.swing.JRadioButton jRadioButtonNao;
    private javax.swing.JRadioButton jRadioButtonSim;
    private javax.swing.JTextField txtNomeEstado;
    // End of variables declaration//GEN-END:variables
}
